### ISSUE TITLE
关于功耗问题

### ISSUE THREAD

**Issue by Likenttt** [yihong0618/iBeats#2]
这个一直采集上报数据会不会非常耗电啊.

**Comment by yihong0618** [comment]
不一直采集，是捷径运行才会采集。这个的母项目小米手环是一直采集的。

**Comment by Likenttt** [comment]
> 不一直采集，是捷径运行才会采集。这个的母项目小米手环是一直采集的。

有点意思, 可以做个garmin widget. 在background定时发送http请求.甚至不需要shortcuts

**Comment by yihong0618** [comment]
完全可以，这个你熟悉了哈哈^_^
