### ISSUE TITLE
关于如何定时自动更新的疑惑

### ISSUE THREAD

**Issue by Kilerd** [yihong0618/iBeats#3]
看到了通过shortcut 来获取health 里面的心率数据，但是是通过何种方式自动触发更新的呢？

我了解到的shortcut 里面的自动化只能指定一个时间来自动执行某个shortcut，那么如果要达到如同cron 的效果（例如每5分钟一次）的话，那要如何做到呢？

**Comment by yihong0618** [comment]
有几种方案：

1. 你说的指定时间，多指定些自动时间。但需要先写 shortcuts, 然后再一个时间一个时间加
2. 邮件是可以触发的，利用 actions 自动给自己发邮件 crontab 但是这个我放弃的原因是邮件触发必须手动确认
3. shortcuts 是可以写循环的，但这个方案非常费电
4. 关闭或打开某个 app 可以触发（比如 things ），有一些 app 会后台没事打开一次，利用这些 app 可以实现，但坏处是他不一定啥时候打开。

**Comment by Kilerd** [comment]
OK，了解。
就是说如果纯粹使用shortcut 里面的「自动化」来实现的话，只能一个一个时间手动指定。
另外就是通过某种定时的event 来触发这个shortcut

理解了，多谢。

**Comment by yihong0618** [comment]
不客气哈哈。
是的，不知道 iOS 为啥没开 crontab 
btw, 我是找了个每日打开都会有频率的 app, 然后关闭触发。

我本来以为邮件触发是很好的方案，但 iOS 又加了邮件必须手动确认的限制。

**Comment by Kilerd** [comment]
是的，我就注意到，你的数据其实更新存在厌恶，比如说我发issue的时候你的数据还停留在07.03 所以就存在疑惑。
